### ISSUE TITLE
let's be opinionated about the default aspect ratio

### ISSUE THREAD

**Issue by esheldon** [biggles-plot/biggles#107]
sometimes the aspect ratio comes out wonky, depending on the axis labels etc.

Let's set the default for the aspect ratio to something besides None.  I think the only choices would be 1.0 or 1/golden_ratio = 0.618

Setting it to 1 would make most of the examples look fairly similar to, but a little better than, the way currently look.  golden ratio is more pleasing in many scenarios.

**Comment by beckermr** [comment]
I vote for the golden ratio.

**Comment by esheldon** [comment]
example1 with golden ratio

![example1-gratiio](https://cloud.githubusercontent.com/assets/621661/24116525/79c1a056-0d7d-11e7-9f15-224b7ba617f0.png)

**Comment by esheldon** [comment]
this messed up example 3 quite a bit; that is an example where letting biggles figure it out works better
![example3](https://cloud.githubusercontent.com/assets/621661/24116621/c4eecbbc-0d7d-11e7-9e8d-67e119ba4886.png)

**Comment by esheldon** [comment]
maybe being less opinionated is better then.

Maybe instead let's add the 1/golden_ratio as a module attribute so it can be used easily.

```python
from biggles import plot, igratio

plot(x, y, aspect_ratio=igratio)
```
this reminds me, wold be good to let `ratio` be an alias for `aspect_ratio` in most cases.

**Comment by beckermr** [comment]
Hmmm. Maybe we could adopt the matplotlib default? Is that 4:3? Not sure.

**Comment by beckermr** [comment]
Matplotlib is 4:3. I think that would be less disruptive.

**Comment by esheldon** [comment]
That's still no good for example 3.

I'm starting to see the wisdom of letting these be free.  I think we should close this one.

![example3](https://cloud.githubusercontent.com/assets/621661/24148796/b0f3bd7c-0e16-11e7-9f2d-ed03203cfce0.png)

**Comment by beckermr** [comment]
Makes sense to me!
