### ISSUE TITLE
more options to FramedArray vs. fixing Table

### ISSUE THREAD

**Issue by beckermr** [biggles-plot/biggles#13]
I had but some of these options in (see FramedArray at changeset 3ff32a1490a69dcd9d815bd73d6a70086f18c344). However, the included code was basically me just hacking apart FramedArray in a somewhat arbitrary manner. 

My proposed additions are
1) separate axes ranges and log vs linear for each panel
2) x and y axis labels for each row and column

The issue I found was that Table with FramedPlots supports some of this functionality already, but that when you set the aligned_interior property, the panel sizes don't look quite right. If we can fix this, then additions to FramedArray outlined above may not be needed.

**Comment by beckermr** [comment]
@esheldon It looks like you have addressed this issue on master? OK to close?

**Comment by esheldon** [comment]
yep
