### ISSUE TITLE
read_matrix dropped from biggles 1.7

### ISSUE THREAD

**Issue by graik** [biggles-plot/biggles#130]
I am using `biggles.read_matrix()` to plot points over a pre-calculated density contour. The code still runs with biggles 1.6.6 but fails with 1.7.2 and the method does not seem to be part of biggles any longer. Has it moved? What's the alternative? I could not find anything in the change log either.

**Comment by beckermr** [comment]
I am very sorry! We should have documented this better. I believe the io routines were deprecated in favor of using a suitable routine from numpy or pandas. 

We don't have a plan to add them back at the moment. 

Thank you very much for creating this issue and commenting. 

I am going to make an issue to update the changelog now. 

Closing but feel free to reopen!

**Comment by graik** [comment]
workaround is to use `numpy.loadtxt( filename )` which, in the case of biskit at least, is a perfect replacement. Would be good to document that somewhere though. Thanks!
