### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by beckermr** [biggles-plot/biggles#131]
Some depreciations from version 1.6 were not documented. This includes read_matrix and probably others.

**Comment by esheldon** [comment]
I don't know what read_matrix did, can we give @graik a suggestion for a replacement?

**Comment by graik** [comment]
`numpy.loadtxt` works as a replacement for me. I am not sure whether all the options are comparable but the default behavior without kwargs seems the same.

**Comment by beckermr** [comment]
Good call @esheldon. Looks like this worked out. Sorry!

**Comment by beckermr** [comment]
Looks like this is in the changelog already. Closing this issue

https://github.com/biggles-plot/biggles/blob/master/CHANGELOG.md#removed-code
