### ISSUE TITLE
get biggles in PyPI and other distribution mechanisms

### ISSUE THREAD

**Issue by esheldon** [biggles-plot/biggles#36]
PyPI should be easy.

We can also potentially add it to debian (and thus ubuntu), fedora, arch, etc. for linux. and homebrew for mac.

**Comment by beckermr** [comment]
@esheldon I think it is time to push out 1.7.0 or even 2? We should push to biggles on pypi.

**Comment by beckermr** [comment]
Also just pypi should be fine.

**Comment by beckermr** [comment]
Done for 1.7.0!
