### ISSUE TITLE
row_fractions, col_fractions auto-scales fonts

### ISSUE THREAD

**Issue by esheldon** [biggles-plot/biggles#5]
I noticed the new feature auto-scales the fonts. e.g. using row_fractions=[0.8, 0.2] gives fonts 0.2 as big for the smaller row.

Should the default behavior be to have uniform font sizes?

**Comment by beckermr** [comment]
@esheldon Are we OK to close this now?

**Comment by esheldon** [comment]
not sure, does it look ok to you now after my hacks?

**Comment by beckermr** [comment]
Is this used on an example? I don't have any code handy...

**Comment by esheldon** [comment]
yes, the new example 10 I added.  Looks ok at first glance.

**Comment by beckermr** [comment]
Mmmk. I will look and then close.

**Comment by beckermr** [comment]
LGTM
