### ISSUE TITLE
Time for a new release (1.6.8)

### ISSUE THREAD

**Issue by smaret** [biggles-plot/biggles#56]
Now that Python 3 is supported, it would be good to make a new biggles release (1.6.8?).

**Comment by smaret** [comment]
Any ETA on this?

**Comment by nolta** [comment]
Is the plan to release 1.6.8 or 1.7.0?

**Comment by esheldon** [comment]
I think there are a few open issues we should address first.  Fixing the default config to not try to reuse windows (which usually causes a seg fault) and figuring out how to recover from a "can't open device" error for X

**Comment by beckermr** [comment]
@nolta @esheldon @smaret I think releasing 1.7.0 is in order. I propose we push to 'biggles' on pypi.

**Comment by beckermr** [comment]
It is now Python 3 compatible so the old name doesn't make sense.

**Comment by esheldon** [comment]
Before release I think we should probably discuss whether we have broken anything :)

The new features are i think backwards compatible.  The new `write()` method, when used to write images, first writes eps and then uses `gs` to convert to an anti-aliased image.  This requires `gs` be installed.  But the old `write_image` is still available, so this is I think OK.

Have you verified that the log axis fixes give the exact same images as before?

Anything else?

**Comment by beckermr** [comment]
I will double check the examples though I am not sure having them be exactly the same should be a requirement. 

I cannot think of anything else. We should update the change log of course and also maybe remove the todo file.

**Comment by beckermr** [comment]
Closing in favor of #74
