### ISSUE TITLE
Clean out the branches

### ISSUE THREAD

**Issue by beckermr** [biggles-plot/biggles#62]
@esheldon Let's clean out the branches.

We can delete the python3 and realobject ones, right?

**Comment by beckermr** [comment]
@esheldon I am bumping you on this one. Is it ok to dump these branches?

**Comment by esheldon** [comment]
I think branches can in general be good for history, but I don't feel
strongly in this case.

On 3/2/17, Matthew R. Becker <notifications@github.com> wrote:
> @esheldon I am bumping you on this one. Is it ok to dump these branches?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/biggles-plot/biggles/issues/62#issuecomment-283857041


-- 
Erin Scott Sheldon
Brookhaven National Laboratory erin dot sheldon at gmail dot com

**Comment by beckermr** [comment]
I think one of these branches has been merged. I will delete that one and leave the other.

**Comment by beckermr** [comment]
Both were merged actually.
