### ISSUE TITLE
MAINT turn on master branch protection and require PRs

### ISSUE THREAD

**Issue by beckermr** [biggles-plot/biggles#69]
@esheldon In order to make this all a bit more orderly and avoid bugs, let's switch to PRs with tests before merge? I can turn this on after we merge #63.

**Comment by beckermr** [comment]
I have enabled this @esheldon. No required reviews, but we do have to work in branches and make a PR.

**Comment by esheldon** [comment]
what does it mean in practice?  I have to fork, then make a branch, but send the pull request against master?  Or does the branch have to exist in the nolta repo first and I pull request against that?

**Comment by beckermr** [comment]
I think either will work. As long as we cleanup the branches, making a branch in the main repo for work should be fine.
