### ISSUE TITLE
Release 1.7.0

### ISSUE THREAD

**Issue by beckermr** [biggles-plot/biggles#74]
To do:
 - [x] check that examples look the same with log axes
 - [x] update CHANGELOG
 - [x] remove TODO
 - [x] bump version in code to 1.7.0
 - [x] tag 1.7.0
 - [x] push to pypi

**Comment by beckermr** [comment]
Here is example 10 from before and after the new commits. (The RNG that makes the data is not seeded, hence the different points!)

![screen shot 2017-03-07 at 9 35 10 pm](https://cloud.githubusercontent.com/assets/5296416/23689129/3fd5030a-037e-11e7-9b4e-5957eb66af92.png)

**Comment by beckermr** [comment]
@esheldon See the images above and PR #75 for updates to the `CHANGELOG`.

**Comment by esheldon** [comment]
look the same to me

**Comment by esheldon** [comment]
this reminds me; we could make the default font `HersheySerif` as I used in the examples.  I understand this is a matter of style, but one nice thing is that is the default font in supermongo, so maybe sm users would want to try out biggles :)

**Comment by beckermr** [comment]
Sounds good.

**Comment by beckermr** [comment]
Done.

**Comment by esheldon** [comment]
ahh, I was going to do it!

I was also going to bump the default screen size to 640/640 or higher since screens are much higher resolution these days.

**Comment by beckermr** [comment]
Sorry! It was easier for me to add it in the PR I had going. I am going to bump the screen size now too.

**Comment by beckermr** [comment]
@esheldon I bumped the screen size too. Feel free to add anything else to the branch I have going for 1.7.0.

**Comment by beckermr** [comment]
@nolta we plan to push to biggles on pypi. Do you want to take down or deprecate the python2-biggles entry? I don't care either way.

**Comment by nolta** [comment]
I've deleted the entry.

**Comment by beckermr** [comment]
Thanks @nolta!

**Comment by beckermr** [comment]
Done!
