### ISSUE TITLE
Auto pep8 the code

### ISSUE THREAD

**Issue by beckermr** [biggles-plot/biggles#79]
I hate myself for saying this, but a lot people expect pep8 looking code. Biggles is def not very pep8 ish. I am ok with 120 character lines.

**Comment by esheldon** [comment]
I think the biggest issue I have is the opaqueness.  The code is highly general, which is good if you already know how it works, but since I don't a lot of it seems like magic.  Maybe as part of the

**Comment by beckermr** [comment]
Looks like your message was cutoff. I agree. The objects are quite opaque. Docs would help, but the layered inheritance structure hides methods.

**Comment by beckermr** [comment]
This issue is related to #19. I will make a separate issue for cleaning up the object structure.
