### ISSUE TITLE
Pip installation failure with biggles 1.7.1 

### ISSUE THREAD

**Issue by smaret** [biggles-plot/biggles#96]
That's probably related to fd99868646ff23f82a1530dfb2f22323007664b1.  I don't understand why the build passes on Travis CI though?

```
% pip2.7 install biggles
Collecting biggles
  Downloading biggles-1.7.1.tar.gz (126kB)
    100% |████████████████████████████████| 133kB 3.3MB/s 
    Complete output from command python setup.py egg_info:
    found plot.h in /usr/local/include
    found libplot in /usr/local/lib
    found libX11 in /usr/X11/lib
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/r2/zwnv7zsd4bd99mqkn4mhqxn800034l/T/pip-build-kNIDLT/biggles/setup.py", line 157, in <module>
        fp = open('README.rst', 'r')
    IOError: [Errno 2] No such file or directory: 'README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/r2/zwnv7zsd4bd99mqkn4mhqxn800034l/T/pip-build-kNIDLT/biggles/
```

**Comment by beckermr** [comment]
Wow. I am really sorry! 

This is a manifest issue. See here https://travis-ci.org/biggles-plot/biggles/jobs/210837395#L586. 

The build passes because it pulls the code from github. 

I will fix it tonight again. I am going to rerelease 1.7.2. 

Again I am really sorry about this! Thank you so much for your patience and the bug reports!

**Comment by smaret** [comment]
Thanks!

**Comment by beckermr** [comment]
OK @smaret. This fix should be up on PyPI in the next hour or so. I am very sorry again for the poor packaging. I think moving to a system which pushes release to a test a branch and then runs additional tests before the main push to PyPI might be worth it.
